inherit_from: https://raw.githubusercontent.com/trinhngocthuyen/templates/main/config/rubocop/default.yaml

Metrics/ClassLength:
  Max: 500

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/RedundantReturn:
  Enabled: false
