# --------------------------------------------------
# Base configs
# --------------------------------------------------
@checksum = "dummy-checksum-to-prevent-merge-conflicts"
ios_deployment_target = "16.0"

platform :ios, ios_deployment_target
use_frameworks! :linkage => (ENV["LINKAGE"] || :static).to_sym
install! "cocoapods", :generate_multiple_pod_projects => true

# --------------------------------------------------
# Plugin configs
# --------------------------------------------------
plugin "cocoapods-spm"
plugin "cocoapods-xcconfig-hooks"
config_compact_spec(
  extra: ->(s) { s.ios.deployment_target = ios_deployment_target }
)

config_cocoapods_spm(
  default_macro_config: "debug"
)

# --------------------------------------------------
# Pods config
# --------------------------------------------------

def shared_pods
  pod "Logger", :path => "LocalPods/Logger"
  pod "Wizard", :macro => { :path => "LocalPackages/ex-macros" }
end

target "EX" do # rubocop:disable Metrics/BlockLength
  shared_pods
  pod "CommonUI", :path => "LocalPods/CommonUI"
  pod "Services", :path => "LocalPods/Services", :testspecs => ["Tests"]

  pod "Orcam", :macro => {
    :git => "https://github.com/trinhngocthuyen/orcam.git",
    :branch => "main",
  }
  pod "MacroCodableKit", :macro => {
    :git => "https://github.com/mikhailmaslo/macro-codable-kit",
    :tag => "0.3.0",
  }

  spm_pkg "SnapKit",
          :url => "https://github.com/SnapKit/SnapKit.git",
          :version => "5.7.1",
          :products => ["SnapKit-Dynamic"]
  spm_pkg "SwiftUIX", :git => "https://github.com/SwiftUIX/SwiftUIX.git", :tag => "0.1.9"
  spm_pkg "SwiftyBeaver",
          :git => "https://github.com/SwiftyBeaver/SwiftyBeaver.git",
          :up_to_next_major_version => "2.0.0"
  spm_pkg "opentelemetry-swift",
          :git => "https://github.com/open-telemetry/opentelemetry-swift.git",
          :branch => "main",
          :products => ["OpenTelemetrySdk"]
  spm_pkg "GoogleMaps",
          :git => "https://github.com/googlemaps/ios-maps-sdk.git",
          :version => "9.3.0",
          :products => ["GoogleMaps"]
  spm_pkg "mqtt-nio",
          :url => "https://github.com/swift-server-community/mqtt-nio.git",
          :version => "2.11.0",
          :products => ["MQTTNIO"]
  spm_pkg "DebugKit", :path => "LocalPackages/debug-kit"
end

target "EXTests" do
  # Nothing here
end

target "EXMac" do
  platform :osx, "14.0"
  shared_pods
end

post_install do |installer|
  installer.native_targets.each do |target|
    target.build_configurations.each do |config|
      # Custom build settings goes here
    end
  end
end
